Create layout for easily deleting website users over the API.
Voog/voog-liquid-examples pull request #1
Opened 2021-03-03 11:58 UTC by pxska

2021-03-04 10:17 UTC, tambeta requested changes
Hea töö. Panin mõned kommentaarid nii üldisemate praktikate kui konkreetse arenduse osas.

2021-03-04 10:17 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +  <body class="content-page{% if editmode or site.has_many_languages? %} lang-enabled{% endif %} {% if flags_state %}flags-enabled{% else %}flags-disabled{% endif %}">
Kuna koodi kirjutatakse inimestele, mitte masinatele, siis võiks read igal pool alla 100 tähemärgi hoida, muidu on see üsna loetamatu (loetavus peab säilima ka mitteoptimaalsetes tingimustes, nt kell 2 öösel :). Siin saaks nt (käsita seda pseudokoodina, ma pole Liquidi-spets):

```liquid
{% if editmode or site.has_many_languages? %}
  {% assign lang-enabled="lang-enabled" %}
{% endif %}

{% if flags_state %}
  {% assign flags="flags-enabled" %}
{% else %}
  {% assign flags="flags-disabled" %}
{% endif %}

<body class="content-page {{lang-enabled}} {{flags}}">
```

2021-03-04 10:17 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +        <div class="addUser">
CSS klasside nimed on traditsiooniliselt kebab-case, e siin `add-user`.

2021-03-04 10:17 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +            id="emailToBeAdded"
DOM ID-d samuti olenevalt koodibaasist kebab-case v snake-case, siin nt `email_to_add` või `email-to-add`.

2021-03-04 10:17 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +            {% if editor_locale == 'et'%}Soovid lisada e-posti aadressi?:{% else %}Add an e-mail address:{% endif %}
Pakun välja parema mustri: selle asemel et igal pool mürast `if` / `else` klauslit kasutada, määra tõlked kuskil päises:

```liquid
{% if editor_locale == 'et'%}
  {% assign str_add_email = "Soovid lisada e-posti aadressi?:" %}
  ...
{% else %}
  {% assign str_add_email = "Add an e-mail address:" %}
  ...
{% endif %}
 
...

<label>{{str_add_email}}</label>
```

2021-03-04 10:17 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +      }
Siin oleks samuti tõlgete haldamiseks kenam muster:

```js
const translationStrings = {
  et: {
    emailTable: 'E-posti aadress',
    //...
  },
  en: {
    emailTable: 'E-mail address',
    //...
  },
}

const tr = key => (translationStrings[language] || {})[key];

// ...

const translatedEmailAddress = tr('emailTable');
```

Märkusena: Transpilaatorist läbi minevas koodis või uutes brauserites otse saaks `tr` lahendada nii:

```js
const tr = key => translationStrings[language]?.[key];
```

Vt. [Optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

2021-03-04 10:17 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +          let value = $(this).val().toLowerCase();
Konstandid peaks olema ka defineeritud kui `const`.

2021-03-04 10:17 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +          });
Siin võiks `filter` asemel `each` kasutada selgema kommunikatsiooni mõttes. `filter` viitab sellele, et sa ka kasutad tagastatavat väärtust.

2021-03-04 10:17 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +          let list_html = "<table><thead><tr><th>" + emailTable +
Uues koodis kasutame üldiselt [interpoleerivat _string literal_ süntaksit](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) sõnede kokkuliitmise asemel, mis on juba üsna OK toega brauserites. Aga jah, siin oleneb kui vanu brausereid toetada tuleb.

```js
let listHtml = `<x>${emailTable}</x>`
```

2021-03-04 10:17 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +          });
Maitse asi, aga ise eelistan listi transformeerimiseks `map` või `reduce`, on veidi puhtam mu silmale:

`const body = users.map(user => ...).join('');`

ja kokku

```js
const header = `<table><th>...`;
const body = users.map(user => ...).join('');

$('.userList').html(`${header}${body}</tbody></table>`);
```

2021-03-04 10:17 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +          $(".userList").html(list_html);
Meil on üldiselt kombeks JS sõned ühekordsete jutumärkidega defineerida (`'.userList'`).

2021-03-04 10:17 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +        let id = $(this)[0].attributes['data-id'].value; // User ID delete nupust
Kommentaarid peaks ka ingliskeelsed olema.

2021-03-04 10:17 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +        }).then(function (users) {
Kuidagi peaks raporteerima ka veaolukorrad, ehk lisaks `then` callbackile ka [`catch`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch). Seda kõigi päringute juures.

2021-03-04 10:17 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +        let emailAddress = $("#emailToBeAdded")[0].value;
Siin tuleks kontrollida, et väärtus ei oleks tühi sõne ning võib-olla ka esmane validatsioon (kas on e-posti aadress?). Validatsioon ei pea olema perfektne, aga "dsdsdsdsd" võiks mitte läbi lasta.

2021-03-04 10:17 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +          error: function (jqXHR) {
Kuna eduolukorra käsitlemiseks on kasutusel `then` tagastatava Promise otsas, siis sümmeetria mõttes võiks veaolukorda käsitleda `catch`.

2021-03-04 10:17 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +            if (jqXHR.status === 422) {
HTTP/422 ei pruugi tingimata tähendada seda, et kasutaja on juba olemas. Peaks eraldi kontrollima, kas tegu on selle veaolukorraga. Muul juhul (sh kui veakood on midagi muud), võib väljastada mingi üldise veateate, aga kasutajale tuleks see kommunikeerida.

2021-03-05 11:16 UTC, pxska commented on site-user-management/layouts/api_user_deletion.tpl
> +          });
Silmale tundub minulgi `map` kasutamine lihtsam, kuid jätsin hetkel algse versiooni -- minu jaoks rohkem arusaadav.

2021-03-08 11:12 UTC, tambeta requested changes
Hea stuff. Teen mõned ettepanekud koodi viisakamaks refaktoorimiseks. Lisaks leidsin ühe loogikavea.

2021-03-08 11:12 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +      const translatedSomethingWentWrong = tr('somethingWentWrong');
Neid konstante pole vaja, kuna tundub et kasutad suuremat osa vaid korra. See teeb koodi mürasemaks ilma kasuta. Nt. `translatedDeleteButton` on küll kasutusel tsüklis, nii et mikroskoopilise jõudluskasvu sealt ehk ka saab, sel juhul õigustatud.

2021-03-08 11:12 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +              // Make a table
Sellised kommentaarid on kasutud, sest koodist on peale vaadates üheselt selge, mida see teeb. See on hea koodi tunnus, aga seda eraldi proosas kirjeldada pole tarvis. Vt. nt. [Google'i soovitusi heade kommentaaride kirjutamiseks](https://developers.google.com/tech-writing/two/code-comments).

2021-03-08 11:12 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +              // Add each user to the table
Sama siin.

2021-03-08 11:12 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +          let id = $(this)[0].attributes['data-id'].value; // Get the User ID from the delete button
Tundub, et need on konstandid, seega võib defineerida kui `const`. Vaata palun selles osas ka ülejäänud muutujate definitsioonid üle. Vormistuse osas on siin vaherida liiast ja samuti kommentaarid, aga see on jälle maitse asi. (Vormistuse detaile jõustab suurtes koodibaasides meil üldiselt linter, kasutame [ESLint](https://eslint.org/) + [Prettier](https://prettier.io/) kombot.)

2021-03-08 11:12 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
>        function getUsers() {
Programmi oleku globaalses muutujas säilitamise asemel (halb muster) saaks `getUsers` tagastada [`Promise`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), mille lahendusväärtus on kasutajate või e-posti aadresside loend. See võimaldaks `allUsers` muutujast lahti saada.

Teine antimuster siin on, et funktsioon üritab teostada mitut ülesannet ning sisu ei vasta (täielikult) nimele. `getUsers` peakski (läbi `Promise`) tagastama kasutajate listi ning käsitlema veaolukorda. Eraldi funktsioon `buildTable` vms tegeleks tabeli koostamisega.

Ehk:

```js
const getUsers = () => new Promise((resolve, reject) => {
  $.ajax(...)
    .then(users => {/* ... */; resolve(users);})
    .catch(xhr => {/* ... */; reject();})
}};

// --- //

const buildTable = emails => {
  // pane massiivi `emails` põhjal tabel kokku ja sisesta DOM-i
};

// --- //

getUsers().then(buildTable);
```

2021-03-08 11:12 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +                      }
Siin on uue päringu tegemine puhtalt veaolukorra käsitlemiseks liiast. Halvemal juhul lendab uus päring ka orki. Vaata palun [API dokumentatsioonist](https://www.voog.com/developers/api/resources/site_users) detaile ja katseta laivis; see päring annab _payload_'is kindlasti tagasi konkreetse vea kirjelduse. 

Tõsi, probleem on see, et meil pole API-s ühtsust veakoodide (a la `duplicate_user`) ja inimloetava teksti osas (ideaalis peaks tagastama mõlemad). Kui tagastatkse ainult tõlgitud sõne siis pole meil kindlust, millises keeles see on nii et tuleb kasutada mingit heuristikat. Panen ette kontrollida, kas tagastatava struktuuri `errors` objektis on võti `email` ning kui on, anda kasutajale veateade stiilis "E-posti aadress ei ole korrektne või on juba lisatud.".

Teine probleem on see, et e-posti aadressi võrdsus ei ole sama mis sõne võrdsus. Ehk `allUsers.includes(emailAddressToAdd)` ei püüa kinni juhtu, kus kasutaja sisestab alguses `me@example.com` ja pärast `me+test@example.com`. Server võib, aga ei pruugi, neid võrdsetena käsitleda. (Konkreetselt meie backendi juhul [ei ole need võrdsed](https://github.com/Edicy/edicy_cms/blob/master/app/models/site_user.rb#L14), seega siin üldise tähelepanekuna.)

Kolmandaks, sa näikse tegevat eelduse, et kohe pärast `getUsers` välja kutsumist on `allUsers` sisustatud värske listiga. Nii see kindlasti asünkroonse koodi puhul ei ole — `getUsers` peaks tagastama [`Promise`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), mille positiivse lahendumise puhul oleks `allUsers` värskus garanteeritud. Lisaks on siin kasutusel habras muster, kus kood toetub globaalse muutuja väärtusele. Selles osas vt. kommentaari `getUsers` juures.

2021-03-08 11:12 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +          $('#search').on('keyup', function () {
Sul on siin kuulaja külge pandud pärast dokumendi laadimist, aga teisi kuulajaid seod varem (mis töötab, sest need lähevad `document` külge, aga lugeda on koodi ebamugav). Samuti on kasutajate laadimine ja tabeli kokku panemine isoleeritud eraldi funktsiooni, aga teised operatsioonid mitte. Panen ette JS kood ühtlustada järgmise kondikavaga:

```js
<script>

  // ülemisel tasemel ainult tõlgetega seotud muutujad ja funktsioonide definitsioonid
  
  const translationStrings = ...;
 
  // init() seob kõik kuulajad

  const init = () => document.ready(() => {
    $('#search').on('keyup', searchTable);
    $(document).on('click', '.delete', deleteUser);
    // ...
  });

  // kogu loogika selgete ülesannetega funktsioonidesse eraldatud

  const getUsers = () => ...;

  const deleteUser = () => ...;

  const buildTable = () => ...;

  // ...

  // lõpuks kutsud `init` välja ja paned kogu joga käima
    
  init();
</script>
```

2021-03-08 11:46 UTC, siimha requested changes

2021-03-08 11:46 UTC, siimha commented on site-user-management/layouts/api_user_deletion.tpl
> +    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
Kuna lisad siin näites ka javascripti komponendi, kus on ka jquery, siis pole seda eraldi vaja kasutada, kui liiguta jquery funktsioonid javascripti komponendi järele.

2021-03-08 11:46 UTC, siimha commented on site-user-management/layouts/api_user_deletion.tpl
> +    {% include "javascripts" %}
Need includitud komponentide nimetused ei ole kõikides mallides samad ja võiks kommentaari juurde panna.

2021-03-10 11:13 UTC, pxska commented
Mul on veel paar _edge case_'i, mida ma päris täpselt ei osanud lahendada, aga võivad osutuda problemaatiliseks: kasutajat, millega on sisse logitud ning kasutajat, kes veebilehe lõi, ei tohiks saada kustutada. Kuidas seda saaks kontrollida, mis kasutajaga veebilehele sisselogitud on? Samuti oleks vaja kuidagi kontrollida, et kasutaja on omanikustaatuses, sest toimetajastaatuses ei saa seda liidest kasutada, aga API `POST` päring ei andnud ka mingit tulemust, kui proovisin toimetajana kasutajaid lisada ja eemaldada.

Esimese probleemiga seoses: Näiteks kui ma olen enda testlehe loonud `kristjanparnmets` e-posti aadressiga ning olles selle kasutajaga sisselogitud kustutasin selle ära, siis ei juhtunud midagi. **Seaded** > **Kasutajad** all näitas ikka, et see kasutaja on olemas, aga `site_users` all mitte. Samuti ei saanud ma oma liidese kaudu seda kasutajat tagasi lisada.

2021-03-10 13:32 UTC, tanelj commented
> Mul on veel paar _edge case_'i, mida ma päris täpselt ei osanud lahendad

Siin on segi läinud mõisted Person ja SiteUser
* Person - saidi haldaja (owner või editor) ([People API](https://www.voog.com/developers/api/resources/people)). Üle API ainult read only.
* SiteUser - parooligakaitstud lehtedele ligi pääsev kasutaja ([SiteUser API](https://www.voog.com/developers/api/resources/site_users), ei ole mingit seost saidi haldajaga. Sama meil saab olla nii saidi haldajate kui parooliga kaitstud lehtede kasutajate hulgas.

See PR tegeleb SiteUseriga seega välja toodud edge case'id ei ole teemaks.

2021-03-10 14:04 UTC, tambeta requested changes
Mõned kommentaarid veel, suuremalt jaolt vormistamise detailid jäänud.

2021-03-10 14:04 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +    {% assign lang-enabled = "lang-enabled" %}
Miks siin ja edaspidi treppimise ära kaotanud oled? Tüüpiliselt on koodis `if` / `else` blokid ikka sisse trepitud.

2021-03-10 14:04 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +        const target = (e.target) ? e.target : e.srcElement;
Siin piisab

```js
const target = e.target || e.srcElement;
```

2021-03-10 14:04 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +              if (xhr.responseJSON.errors.email[0] === "has already been taken") {
Nii kontrollida ei saa. Kui sisselogitud kasutaja keel ei ole inglise, siis kukub see läbi (kuna ka API veateated on tõlgitud). Selgitasin seda eelnevalt — siin saad ainult kontrollida, kas `email` võti on olemas või mitte. See on meie API vajakajäämine.

2021-03-10 14:04 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +              data: `{\"email\" : \"${emailAddressToAdd}\"}`,
Viisakam on siin teha 

```js
JSON.stringify({email: emailAddressToAdd})
```

mitte üritada JSON-it käsitsi kokku panna. Aga ma arvan, et piisab ka

```js
data: {email: emailAddressToAdd}
```

sest kujutaks ette, et jQuery oskab JSON kodeerimise ise ära teha.

2021-03-10 14:04 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +            });
See lõik ei tee midagi?

2021-03-10 14:04 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +          list_html += `<tbody id='user-table'>
Siin lisad nüüd tsükli igal sammul `<tbody>`.

2021-03-10 14:04 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +        const target = (e.target) ? e.target : e.srcElement;
Siin piisab samuti

```js
const target = e.target || e.srcElement;
```

2021-03-10 14:04 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +            getUsers().then(buildTable);
Siin ei ole mõtet uut päringut teha. Ma arvan, et eelnev lähenemine, kus lihtsalt vastava tabeli rea ära kustutasid, on OK.

2021-03-10 14:04 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +      getUsers().then(buildTable);
Kenam oleks see ka `init` funktsiooni tõsta.

2021-03-11 19:04 UTC, tambeta approved these changes
Väga hea! Ma rohkem ei nori.

2021-03-12 09:06 UTC, tanelj requested changes
Kena, kui eeldustest võiks lahti saada. St peaks olema nö drop in eraldiseisev layout:

* Ei tohiks `include` komponente olla.
* On puhtalt oma stiilidega kuvatav (ei võta sisse saidi stiile) (üleliigsed klassi nimed eemaldada)
* Lehe pealkiri nt tõlkest, mis ütleb, milleks see leht on.
* Päises link tagasi esilehe <a href="/">{{ str_home | escape_once }}</a>

2021-03-12 09:06 UTC, tanelj commented on site-user-management/layouts/api_user_deletion.tpl
> +  <meta http-equiv="refresh" content="0; url=/" />
Ka mitte edit mode HTML peaks valiidne olema.

```html
<!DOCTYPE html>
<head>
  <meta http-equiv="refresh" content="0; url=/" />
  <title>Redirect</title>
</head>
</html>
```

2021-03-12 09:06 UTC, tanelj commented on site-user-management/layouts/api_user_deletion.tpl
> +      {% if editmode or site.has_many_languages? %}
Kood ei ole vajalik - teeb eelduse, et üldises kujunduses on olemas  `lang-enabled` stiil.

2021-03-12 09:06 UTC, tanelj commented on site-user-management/layouts/api_user_deletion.tpl
> +  {% include "template-variables" %}
Eeldab, et kujunduses on olemas `template-variables` komponent. Ei tohiks eeldada ja tuleks eemaldada.

2021-03-12 09:06 UTC, tanelj commented on site-user-management/layouts/api_user_deletion.tpl
> +        {% include "header" %}
Eeldab, et kujunduses on olemas `header` komponent. Ei tohiks eeldada ja tuleks eemaldada.

2021-03-12 09:06 UTC, tanelj commented on site-user-management/layouts/api_user_deletion.tpl
> +      {% include "javascripts" %}
Taas range eeldus - ei ole vaja ja tuleks eemaldada.

2021-03-12 09:06 UTC, tanelj commented on site-user-management/layouts/api_user_deletion.tpl
> +            <label for="email">{{ str_add_email }}</label>
Siin hetkel otsest probleemi ei teki, kuid siin ja all pool, kus on kasutatud sisse renderdatud stringe oleks korrektne väärtus escape'ida (a la `>`, `<`, `"` märgid: https://www.voog.com/developers/markup/basics/filters#escape_once

```liquid
{{ str_add_email | escape_once }}
```

2021-03-12 09:06 UTC, tanelj commented on site-user-management/layouts/api_user_deletion.tpl
> +        {% include "footer" %}
Taas range eeldus - ei ole vaja ja tuleks eemaldada.

2021-03-12 09:06 UTC, tanelj commented on site-user-management/layouts/api_user_deletion.tpl
> +            <input type="email" id="email-to-add" name="email" placeholder="email@email.com">
Tuleks kasutada `type="email"`, mis tegeleb juba browseri poolse valideerimisega https://www.w3schools.com/tags/att_input_type_email.asp

2021-03-12 09:06 UTC, tanelj commented on site-user-management/layouts/api_user_deletion.tpl
> +          const regexp = /^([\w\d._\-#])+@([\w\d._\-#]+[.][\w\d._\-#]+)+$/;
Tundub esmapilgul üleliigne, kui väljal on `type="email"`, mis tegeleb juba browseri poolse valideerimisega https://www.w3schools.com/tags/att_input_type_email.asp

2021-03-12 09:06 UTC, tanelj commented on site-user-management/layouts/api_user_deletion.tpl
> +        const language = document.getElementsByTagName('html')[0].getAttribute('lang');
Siin vaja falbacki. Nt kui tõlget ei ole (a la leht on norra keelsel alalehel):

```js
if(translationStrings[language] === undefined) {
  language = "en";
}
```

Või
```js
const tr = key => (translationStrings[language] || translationStrings["en"])[key];
```

2021-03-12 09:42 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +          const regexp = /^([\w\d._\-#])+@([\w\d._\-#]+[.][\w\d._\-#]+)+$/;
See ei ole üleliigne, sest `type="email"` validatsiooni läbi kukkumine ei takista minu teada vormi postitamist, vaid lihtsalt lisab `:invalid` CSS pseudoklassi. Samuti on mingil alusel vaja kasutajale veateadet kuvada. Need täiendavad üksteist; väljale võiks `type="email"` + `required` lisada küll.

2021-03-12 10:59 UTC, pxska commented on site-user-management/layouts/api_user_deletion.tpl
> +          const regexp = /^([\w\d._\-#])+@([\w\d._\-#]+[.][\w\d._\-#]+)+$/;
`type="email"` laseb vist ilma punktita e-posti aadressid ka "läbi", nt `kristjan@voog`, seega see `regex` on seal pigem selline "usalda, aga kontrolli". :-)

2021-03-12 11:27 UTC, tanelj commented on site-user-management/layouts/api_user_deletion.tpl
> +          const regexp = /^([\w\d._\-#])+@([\w\d._\-#]+[.][\w\d._\-#]+)+$/;
`kristjan@voog` on tegelikult valiidne emaili aadress, kuigi tõesti mitte siin kontekstis :) 

https://en.wikipedia.org/wiki/Email_address#Examples
https://regexr.com/

Kui siin regex'i kasutada, siis peaks see vastama enam vähem sellele, mida ka backend valideerib (seal tõesti `#` märki me ei luba, kuid nt `test+test@gmail.com` tuleks ka frondis lubada.

```js
const regexp = /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i; 
```

Kuid kuna API nagunii valideerib ka emaili formaati siis peaks piisama (type="email").

Valideerimisviga peab handlima JS. Vigase emaili korral:

```json
{
    "message": "An error occurred when inviting this site user. Please review the fields.",
    "errors": {
        "email": [
            "is invalid"
        ]
    }
}
```

Olemasoleva korral:
```json
{
    "message": "An error occurred when inviting this site user. Please review the fields.",
    "errors": {
        "email": [
            "has already been taken"
        ]
    }
}
```

2021-03-12 11:49 UTC, pxska commented on site-user-management/layouts/api_user_deletion.tpl
> +          const regexp = /^([\w\d._\-#])+@([\w\d._\-#]+[.][\w\d._\-#]+)+$/;
Tegin [Tambeti varasemal soovitusel](https://github.com/Voog/voog-liquid-examples/pull/1#discussion_r589333085) ühe üldise errori ehk nüüd saab kasutaja errori, kui see on juba olemas või midagi läks valesti. `regexp` muutsin ka igaks juhuks backendi validatisoonile kohaseks.

2021-03-15 07:09 UTC, siimha approved these changes
Tubli!

2021-03-15 07:57 UTC, tanelj requested changes
Hetkel ei täida lahendus kõige olulisemat eesmärki, milleks teda tarvis oli:

* Võimalus hallata kasutajaid, kui saidil on üle 250 (API päringu maksimaalne [API per_page](https://www.voog.com/developers/api/basics/pagination)) SiteUser objekti. Vaikimis laetakse 50 objekti.

Siin on kaks võimalikku lahendust:
1) Laadida lehe avamisel kõik kasutajad (nt teha `/admin/api/site_users?s=site_user.email&per_page=250` päringuid seni, kuni tagastatav kaustajate array on tühi; kasutades [Links headerit](https://www.voog.com/developers/api/basics/pagination)). Sel juhul laetakse andmed alguses ning lookup loogika jääb samaks.
2) Kohendada lookup loogikat nii, et nt peale 3 tähemärki tehakse igal klahvisisestusel API päring kasutades [filtriks](https://www.voog.com/developers/api/basics/filters), kas alguse match'i `$starts` või sisalduvust `$cont`.
```
/admin/api/site_users?s=site_user.email&per_page=10&q.site_user.email.$cont=LOOKUPSRT
```

2021-03-15 07:57 UTC, tanelj commented on site-user-management/layouts/api_user_deletion.tpl
> +        {% assign str_title = "Deleting users of password-protected pages over API" %}
Korrektsem oleks "Manage users of password-protected pages" - API on tehniline ja ei ole kasutaja jaoks oluline.

2021-03-15 07:57 UTC, tanelj commented on site-user-management/layouts/api_user_deletion.tpl
> +        {% assign str_title = "Parooliga kaitstud lehtede kasutajate kustutamine üle API" %}
Korrektsem oleks "Parooliga kaitstud lehtede kasutajate haldamine" - API on tehniline ja ei ole kasutaja jaoks oluline.

2021-03-15 07:57 UTC, tanelj commented on site-user-management/layouts/api_user_deletion.tpl
> +    <title>{{str_title}}</title>
`title^ tagi (mõeldud browseri tabis nime kuvamiseks ainus [lubatud parent](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title) on `head` tag. Hetkel on `title` tag HTML'i sees. 

Head tagis on title ka kohustuslik element.

Pealkirja kuvamiseks lehel tuleks kasutada `h1` tagi ning seda `body` sees.

2021-03-15 07:57 UTC, tanelj commented on site-user-management/layouts/api_user_deletion.tpl
> +      <style>
Lisaks ka back lingile värvi (mis katab ka :visited värvi). Nt
```
        a {
          color: #443df6;
        }
```

2021-03-15 07:57 UTC, tanelj commented on site-user-management/layouts/api_user_deletion.tpl
> +
Kuvaks pealkirja ka lehel.

```
<h1>{{str_title}}</h1>
```

2021-03-15 07:57 UTC, tanelj commented on site-user-management/layouts/api_user_deletion.tpl
> +              url: '/admin/api/site_users',
Tagastatavad kasutajad peaksid olema emaili järgi sorteeritud:

```
/admin/api/site_users?s=site_user.email
```

2021-03-17 14:14 UTC, tanelj requested changes
Saadan veel viimast korda tagasi, sest üks juht ei toimi (nt proovi per_page=2):

* Kui lähen lehele ning otsin emaili, siis emaili ei leita, kui andmed on mitmel lehel, email ei sisaldu algsel lehel ning kasutaja ei ole veel teise lehe (page) peal klikanud.

Siin soovitaks kasutajale lehtede näitamisest loobuda ning teha nii, et `getUsers` laeb kohe lehtede andme ühte pikka tabelisse ära.

2021-03-22 12:11 UTC, tambeta requested changes

2021-03-22 12:11 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +              }
Siin on kaks teemat segamini läinud. Funktsioon peaks tegema ühte asja, tegema seda hästi ja vastama oma nimele. Ehk siin ei peaks üldse DOMi puutuma ja kogu tabeli konstrueerimise `addToTable` hooleks jätma. Viimasele võid ette anda parameetri a la `init` või `empty` et see tühjendada. ` $('#user-table-table').append('</tbody></table>')` rida ja vastav `if` haru on üldse ebavajalik, sest see peaks alati DOM-is olemas olema ning muudad sa ainult `tbody` sisu.

Teiseks teed siin üleliigseid päringuid. Näiteks kui lk-de arv on 1, siis tehakse algne päring, kutsutakse välja `addToTable` ja tehakse järgmine (üleliigne) päring, mis saab tühja vastuse. Lisaks on siin probleem, et kui lk-de arv on 1, ei tühjendata algset tabelit. Kuid 1 üleliigse päringu probleem on suvalise lk-de arvu puhul.

Samuti ärme kasuta `!=`, v.a. erijuhul kui tahame mingit väärtust `null` ja `undefined` vastu [korraga kontrollida](https://stackoverflow.com/a/15992131).

`pageNumber += 1` on üleliigne, saad otse ette anda `getUsers(pageNumber + 1)`.

`pages` võiks selguse mõttes nimetada `nPages`. `pages` viitab, et muutujas hoitakse mingit lehekülgi esitavat struktuuri.

Kui tahad API päringud jadamisi toimivaks jätta, siis loogika on lihtsalt (`then` callbackis):

```
if (page === 1) {
  addToTable(users, {init: true});
}
else {
  addToTable(users);
}

if (nPages > pageNumber) {
  getUsers(pageNumber + 1);
}
```

või veel kompaktsemalt: 

```
addToTable(users, {init: page === 1});

if (nPages > pageNumber) {
  getUsers(pageNumber + 1);
}
```

Aga proovi ka paralleelseks teha, nagu Slackis arutatud.

2021-03-22 12:11 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +                <tbody id='user-table'>
See ei ole korrektne HTML, `</tbody></table>` puudu.

2021-03-22 12:11 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +          const value = target.value.toLowerCase();
Vormistuse ettepanek: jäta konstantide / muutujate definitsioonide ja järgneva funktsiooni sisu vahele loetavuse huvides tühi rida, siin ja edaspidi.

2021-03-22 12:11 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +            let addTableRow = `<tr>
Seda pole põhjust eraldi muutujana hoida, saad otse `append`-ile ette anda.

2021-03-22 12:11 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +        }
Semikoolon puudu.

2021-03-23 08:40 UTC, tambeta requested changes
Võimas, hakkab lõpusirgele jõudma. Mõned kohendused veel vaja teha.

2021-03-23 08:40 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +              <tbody id='user-table'>
Natuke viisakam nimetamine oleks tabelile `user-table` ja `tbody`-le `user-table-body`.

2021-03-23 08:40 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +            for (let i = 1; i <= nPages; i++) {
Siin peaksid tsüklit alustama 2. leheküljega, sest 1. on sul juba käes esimesest päringust.

2021-03-23 08:40 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +          getUsersPage().then((obj) => {
`obj` on hästi halb muutuja nimi, sest ei kirjelda midagi. Parem nt `usersPage`. (Märkuse korras: sellele reeglile on erandeid, nt väga lühikeses abifunktsioonis, või väljakujunenud kombed (`for` tsüklimuutuja on `i` hiljemalt 70-ndatest, [`reduce`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce) callback-funktsioonis kasutan enamasti `acc` ja `cur` jne))

2021-03-23 08:40 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +              results.forEach((obj, idx) => addToTable(obj.users, {init: idx === 1}));
Eelmise kommentaariga seoses: siit peaksid `addToTable(usersPage, {init: true})` välja tõstma ning tsüklisse jääb väljakutse kujul `addToTable(obj.users)`.

2021-03-23 08:40 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +              resolve({users: users, nPages: pages});
Ettepanek: nimeta eelnev konstant ümber `pages` → `nPages` ning saad siin [shorthand süntaksit](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#new_notations_in_ecmascript_2015) kasutada.

```js
resolve({users, nPages});
```

Kuigi ega eraldi konstandi väärtustamist siin vaja ei olegi.

2021-03-23 08:40 UTC, tambeta commented on site-user-management/layouts/api_user_deletion.tpl
> +        const addToTable = (users, init = false) => {
Funktsiooni signatuur peaks olema

```js
(users, {init = false} = {})
```

kuna eelnevas kutsud seda välja kui `addToTable(u, {init: x})`, mitte `addToTable(u, x)`.

2021-03-23 09:03 UTC, tambeta approved these changes
OK!

2021-03-23 09:42 UTC, tanelj requested changes
Toimib kenasti!

Vaid ühe väikese kommentaari veel lisan.

2021-03-23 09:42 UTC, tanelj commented on site-user-management/layouts/api_user_deletion.tpl
> +        {% assign language = 'et' %}
Eraldi `language` muutujat ei ole sul tegelikult vaja. Siin liquid'i kontekstis sa teda ka ei kasuta. `editor_locale` on juba olemas.

Hetkel kasutad sa `language` muutujat JS osas, kuid seal on sul juba olemas fallback "EN"'ile.

2021-03-23 09:42 UTC, tanelj commented on site-user-management/layouts/api_user_deletion.tpl
> +        const tr = key => (translationStrings['{{ language | escape_once }}'] || translationStrings['en'])[key];
Nagu eespool märkisin, siis kuna siin on fallback olemas, siis eraldi `language` muutujal ei ole mõtet. Seega peaks siin olema:

```liquid
const tr = key => (translationStrings['{{ editor_locale }}'] || translationStrings['en'])[key];
```

2021-03-23 12:54 UTC, tanelj approved these changes

2021-03-24 06:46 UTC, robertpih approved these changes

2021-03-24 06:47 UTC, merged